feat: finalize delworker command in mpk3s and cleanup scripts

diff --git a/mpk3s b/mpk3s
--- a/mpk3s
+++ b/mpk3s
@@ -1,5 +1,6 @@
 #!/bin/bash
 set -e
+# set -x
 
 ## Global Definitions Start ##
 built_in_specs=(
@@ -566,10 +567,10 @@ selected_cluster=""
 select_cluster_list() {
   cluster_list=$(multipass ls | grep master | awk '{print$1}')
   echo "--------------------------------"
-  echo "Cluster name"
+  echo "Cluster name(${selected_cluster})"
   echo "--------------------------------"
   PS3="
-👉 Select cluster : "
+👉 Select cluster: "
   select choice in "${cluster_list[@]}"; do
     if [ -n "$choice" ]; then
       selected_cluster=$(sed -e "s/-master//g" <<< $choice)
@@ -578,29 +579,25 @@ select_cluster_list() {
       echo "⚠️  Invalid selection. Please enter a number from the list above."
     fi
   done
-
-  echo "selected cluster is ${selected_cluster}"
+  # echo "selected cluster is ${selected_cluster}"
 }
 
 selected_worker_list=()
 selected_worker=""
 select_worker_list() {
-  selected_worker_list=$(multipass ls | grep "${selected_cluster}-worker" | awk '{print$1}')
+  # selected_worker_list=$(multipass ls | grep "${selected_cluster}-worker")
   echo "--------------------------------------------------------------------------------------------"
-  echo "Worker name(Type number seperated by space to select workers)"
+  echo -e "No\t$($CMD ls | head -n 1)"
   echo "--------------------------------------------------------------------------------------------"
-
   idx=1
-  available_worker_list=()
-  for i in ${selected_worker_list[@]}; do
-    echo "${idx}) ${i}"
+  while IFS= read -r line; do
+    echo -e "${idx}\t${line}"
+    available_worker_list+=($idx)
     idx=$((idx+1))
-    available_worker_list+=(${i})
-  done
+  done < <(multipass ls | grep "${selected_cluster}-worker")
+  echo "--------------------------------------------------------------------------------------------"
+  read -p "Type number seperated by space to be deleted workers : " selected_worker
 
-  read -p "Select worker : " selected_worker
-
-  validate_selected_worker
 }
 
 will_delete_worker_list=()
@@ -609,18 +606,22 @@ validate_selected_worker() {
     echo "Error: No worker selected"
     exit 1
   else
-    echo "selected worker is ${selected_worker}"
+    echo "selected_worker is ${selected_worker}"
     for i in ${selected_worker}; do
       if [[ "${available_worker_list[@]}" != *"${i}"* ]]; then
         echo "Error: ${selected_cluster}-worker${i} not found"
+        exit 1
       elif [[ -n $i ]]; then
         will_delete_worker_list+=(${i})
+      else
+        echo "Error: Invalid selection. Please enter a number from the list above."
+        exit 1
       fi
     done
   fi
 }
 
-delete_worker() {
+confirm_delete_worker() {
   for i in ${will_delete_worker_list[@]}; do
     echo "${selected_cluster}-worker${i} will be deleted"
     read -p "Delete ${selected_cluster}-worker${i}? It is not recoverable [Y/n]: " isApply
@@ -677,7 +678,8 @@ add_tls_san_config() {
 delete_worker() {
   select_cluster_list
   select_worker_list
-  delete_worker
+  validate_selected_worker
+  confirm_delete_worker
 }
 
 SUB_COMMAND=$1
