Refactor mpk3s: streamline code with 97 additions and 140 deletions

diff --git a/mpk3s b/mpk3s
--- a/mpk3s
+++ b/mpk3s
@@ -17,7 +17,7 @@ built_in_spec_map=(
 
 sub_commands=(
   "init-kubeconfig"
-  "create-cluster"
+  "generate-cluster"
   "tls-san"
   "add-worker"
   "list-clusters"
@@ -25,7 +25,7 @@ sub_commands=(
 )
 sub_command_messages=(
   "Initialize kubeconfig"
-  "Create a new cluster"
+  "Generate a new cluster"
   "Add TLS SAN config to master node"
   "Add a worker to the cluster"
   "List all clusters"
@@ -58,20 +58,20 @@ init_kubeconfig(){
     cat << EOF > $HOME/.kube-config.sh
 #!/bin/sh
 
-KUBE_ROOT=$HOME/.kube
+KUBE_ROOT=\$HOME/.kube
 unset KUBECONFIG
 KUBECONFIG=''
 
-if [ -d $KUBE_ROOT ]; then
-  for i in $(ls -al $KUBE_ROOT | grep config | grep -v "~" | awk '{print$9}'); do
-    if [ -z $KUBECONFIG ]; then
-      KUBECONFIG=${KUBE_ROOT}/${i}
+if [ -d \$KUBE_ROOT ]; then
+  for i in \$(ls -al \$KUBE_ROOT | grep config | grep -v "~" | awk '{print\$9}'); do
+    if [ -z \$KUBECONFIG ]; then
+      KUBECONFIG=\$KUBE_ROOT/\$i
     else
-      KUBECONFIG=${KUBECONFIG}:${KUBE_ROOT}/${i}
+      KUBECONFIG=\$KUBECONFIG:\$KUBE_ROOT/\$i
     fi
   done
 fi
-export KUBECONFIG=$KUBECONFIG
+export KUBECONFIG=\$KUBECONFIG
 EOF
     chmod +x $HOME/.kube-config.sh
     echo "Kubeconfig created"
@@ -80,48 +80,34 @@ EOF
 }
 
 
-
-
 ###### Create Cluster Start ######
-validate_multipass_cmd() {
-  echo "### Validating multipass command.. ###"
+verify_multipass_cmd() {
   if ! command -v multipass &> /dev/null; then
     echo "multipass command not found. Please install multipass first."
     exit 1
-  else
-    echo "multipass command found."
   fi
 }
 
 trap cleanup EXIT ERR
 
+set_cluster_name() {
+  read -p "Enter cluster name(cluster name will be used as k8s cluster(context) name and multipass instance prefix): " CLUSTER_NAME
 
-
-set_context_name() {
-  read -p "Enter context name(Conext name will be used as k8s cluster name and multipass instance prefix): " CONTEXT_NAME
-  echo "Context name is ${CONTEXT_NAME}"
-
-  if [ -z $CONTEXT_NAME ]; then
-    echo "Error: Context name is required"
-    set_context_name
+  if [ -z $CLUSTER_NAME ]; then
+    echo "Error: Cluster name is required"
+    set_cluster_name
   else
-    check_duplicate_context_name
+    check_duplicate_cluster_name
   fi
 }
 
-check_duplicate_context_name() {
-  if [ $(multipass ls | grep ^${CONTEXT_NAME}-master | wc -l) -ne 0 ]; then
-    echo "Error: Context name is aleady used. Please use another name."
-    set_context_name
+check_duplicate_cluster_name() {
+  if [ $(multipass ls | grep ^${CLUSTER_NAME}-master | wc -l) -ne 0 ]; then
+    echo "Error: Cluster name is aleady used. Please use another name."
+    set_cluster_name
   fi
 }
 
-set_worker_size() {
-  read -p "Enter worker size(default: 2): " WORKER_SIZE
-  if [ -z $WORKER_SIZE ]; then
-    WORKER_SIZE=2
-  fi
-}
 
 set_network_name() {
   NETWORK_NAME=$(multipass networks | grep en0 | awk '{print $1}')
@@ -129,7 +115,6 @@ set_network_name() {
 
 # --- ADD: Multipass 이미지 선택 및 multipass 래퍼 ---
 
-# 사용자가 IMAGE/MULTIPASS_IMAGE를 미지정 시 인터랙티브로 이미지 선택
 select_multipass_image() {
   echo "Searching for Ubuntu images..."
   CMD="multipass"
@@ -157,7 +142,7 @@ select_multipass_image() {
 
   # Set prompt for selection
   PS3="
-  👉 Select an image number (or 'q' to quit): "
+👉 Select an image number (or 'q' to quit): "
 
   # Provide selection menu
   select choice in "${IMAGES[@]}"; do
@@ -166,13 +151,11 @@ select_multipass_image() {
           exit 0
       elif [ -n "$choice" ]; then
           # Extract the first column (Image/Alias) as the selected image name
-          IMAGE=$(echo "$choice" | awk '{print $1}')
-          SELECTED_IMAGE=$choice
-
+          IMAGE_NAME=$(echo "$choice" | awk '{print $1}')
           echo ""
           echo "✅ Selection Confirmed!"
           echo "------------------------------------------------"
-          echo "Selected Image: $IMAGE"
+          echo "Selected Image: $IMAGE_NAME"
           echo "Full Detail   : $choice"
           echo "------------------------------------------------"
           break
@@ -180,11 +163,9 @@ select_multipass_image() {
           echo "⚠️  Invalid selection. Please enter a number from the list above."
       fi
   done
-  # echo "Choice image: ${SELECTED_IMAGE}"
+  # echo "Choice image: ${IMAGE_NAME}"
   # return 0
 }
-
-
 
 
 set_custom_master_spec() {
@@ -213,7 +194,7 @@ set_custom_master_spec() {
 
 set_master_spec () {
   PS3="
-  👉 Select master spec : "
+👉 Select master spec : "
   select choice in "${built_in_specs[@]}"; do
     if [ "$REPLY" == "4" ]; then
       set_custom_master_spec
@@ -251,22 +232,6 @@ set_custom_worker_spec() {
   echo "WORKER_SPEC is ${WORKER_SPEC}"
 }
 
-set_worker_spec () {
-  PS3="
-  👉 Select worker spec : "
-  select choice in "${built_in_specs[@]}"; do
-    if [ "$REPLY" == "4" ]; then
-      set_custom_worker_spec
-      break
-    elif [ -n "$choice" ]; then
-      WORKER_SPEC=${built_in_spec_map[$REPLY-1]}
-      break
-    else
-      echo "⚠️ Invalid selection. Please enter a number from the list above."
-    fi
-  done
-}
-
 set_install_k3s_exec() {
   ## 예시 1: etcd + flannel (기본 vxlan)
   ### curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-init" sh -
@@ -275,11 +240,11 @@ set_install_k3s_exec() {
   ### curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--cluster-init --disable=traefik" sh -
   # traefik 비활성화 (Istio 사용을 위해)
 
-  read -p "Use traefik(default: y)? (y/n). If you use istio, disable traefik: " use_traefik
-  read -p "Use flannel(default: y)? (y/n): " use_flannel
-  read -p "Use servicelb(default: y)? (y/n): " use_servicelb
-  read -p "Use local storage(default: y)? (y/n): " use_local
-  read -p "Use metrics-server(default: y)? (y/n): " use_metrics_server
+  read -p "Use traefik? (Y/n): " use_traefik
+  read -p "Use flannel? (Y/n): " use_flannel
+  read -p "Use servicelb? (Y/n): " use_servicelb
+  read -p "Use local storage? (Y/n): " use_local
+  read -p "Use metrics-server? (Y/n): " use_metrics_server
 
   if [ "$use_traefik" = "n" ]; then
     INSTALL_K3S_EXEC="--cluster-init --disable=traefik"
@@ -303,13 +268,12 @@ set_install_k3s_exec() {
     INSTALL_K3S_EXEC="${INSTALL_K3S_EXEC} --disable=metrics-server"
   fi
 
-  echo "INSTALL_K3S_EXEC is ${INSTALL_K3S_EXEC}"
+  # echo "INSTALL_K3S_EXEC is ${INSTALL_K3S_EXEC}"
 }
 
-create_master() {
+generate_master() {
   cat > .master.yaml <<EOF
 package_update: true
-image: ${VM_IMAGE}
 packages:
   - curl
 runcmd:
@@ -317,11 +281,11 @@ runcmd:
   - mkdir -p /etc/k3s
 EOF
 
-  multipass launch --name ${CONTEXT_NAME}-master --cpus 2 --memory 2G --disk 10G --network ${NETWORK_NAME} --cloud-init .master.yaml
+  multipass launch ${IMAGE_NAME} --name ${CLUSTER_NAME}-master ${MASTER_SPEC} --network ${NETWORK_NAME} --cloud-init .master.yaml
   rm -f ./.master.yaml
   echo "Initializing k3s..."
-  MASTER_IP=$(multipass exec ${CONTEXT_NAME}-master -- hostname -I | awk '{print $1}')
-  NODE_TOKEN=$(multipass exec ${CONTEXT_NAME}-master -- sudo cat /var/lib/rancher/k3s/server/node-token)
+  MASTER_IP=$(multipass exec ${CLUSTER_NAME}-master -- hostname -I | awk '{print $1}')
+  NODE_TOKEN=$(multipass exec ${CLUSTER_NAME}-master -- sudo cat /var/lib/rancher/k3s/server/node-token)
 }
 
 generate_workers() {
@@ -334,7 +298,7 @@ runcmd:
   - curl -sfL https://get.k3s.io | K3S_URL=https://${MASTER_IP}:6443 K3S_TOKEN=${NODE_TOKEN} sh -
 EOF
     echo "Launching ${i} worker node"
-    multipass launch --name ${CONTEXT_NAME}-worker${i} ${WORKER_SPEC} --network ${NETWORK_NAME} --cloud-init .worker-${i}.yaml
+    multipass launch ${IMAGE_NAME} --name ${CLUSTER_NAME}-worker${i} ${WORKER_SPEC} --network ${NETWORK_NAME} --cloud-init .worker-${i}.yaml
     rm -f ./.worker-${i}.yaml
   done
 
@@ -342,23 +306,22 @@ EOF
 }
 
 create_k8s_config() {
-  multipass exec ${CONTEXT_NAME}-master -- sudo kubectl get nodes
+  multipass exec ${CLUSTER_NAME}-master -- sudo kubectl get nodes
   echo "Generate k8s config file"
-  multipass exec ${CONTEXT_NAME}-master -- sudo cat /etc/rancher/k3s/k3s.yaml | sed -e "s/127.0.0.1/$MASTER_IP/g" -e "s/default/${CONTEXT_NAME}-context/g" > $HOME/.kube/config-${CONTEXT_NAME}
+  multipass exec ${CLUSTER_NAME}-master -- sudo cat /etc/rancher/k3s/k3s.yaml | sed -e "s/127.0.0.1/$MASTER_IP/g" -e "s/default/${CLUSTER_NAME}-context/g" > $HOME/.kube/config-${CLUSTER_NAME}
   echo "Add following message you're KUBECONFIG env."
-  echo "\$HOME/.kube/config-${CONTEXT_NAME}"
+  echo "\$HOME/.kube/config-${CLUSTER_NAME}"
 }
 
-print_info() {
-  echo "Context name: ${CONTEXT_NAME}"
+confirm_info() {
+  echo "Context name: ${CLUSTER_NAME}"
   echo "NETWORK_NAME name: ${NETWORK_NAME}"
-  echo "WORKER SIZE: $WORKER_SIZE"
-  echo "Multipass image: ${IMAGE}"
+  echo "WORKER SIZE: ${WORKER_SIZE}"
+  echo "Multipass image: ${IMAGE_NAME}"
 
-  read -p "Create cluster? (y/n): " create_cluster
-  if [ "$create_cluster" != "y" ]; then
-    echo "Aborting..."
-    exit 1
+  read -p "Generate cluster? (Y/n): " confirm_generate
+  if [[ "$confirm_generate" == "n" || "$confirm_generate" == "N" ]]; then
+    exit 0
   fi
 }
 ###### Create Cluster End ######
@@ -385,14 +348,14 @@ select_cluster() {
     echo "--------------------------------------------------------------------------------"
 
     PS3="
-    👉 Select an cluster number (or 'q' to quit): "
+👉 Select an cluster number (or 'q' to quit): "
 
     select choice in "${CLUSTERS[@]}"; do
       if [[ "$REPLY" == "q" || "$REPLY" == "Q" ]]; then
         echo "👋 Exiting..."
         exit 0
       elif [ -n "$choice" ]; then
-        CONTEXT_NAME=$(sed -e "s/-master//g" <<< "${choice}")
+        CLUSTER_NAME=$(sed -e "s/-master//g" <<< "${choice}")
         break
       else
         echo "⚠️  Invalid selection. Please enter a number from the list above."
@@ -406,19 +369,6 @@ set_worker_size() {
     WORKER_SIZE=1
   fi
 }
-
-built_in_specs=(
-  "2cpus, 2G memory, 10G disk"
-  "4cpus, 4G memory, 20G disk"
-  "8cpus, 8G memory, 40G disk"
-  "Custom"
-)
-
-built_in_spec_map=(
-  "--cpus 2 --memory 2G --disk 10G"
-  "--cpus 4 --memory 4G --disk 20G"
-  "--cpus 8 --memory 8G --disk 40G"
-)
 
 set_custom_spec() {
   read -p "Enter cpu count: " CPU_COUNT
@@ -444,10 +394,12 @@ set_custom_spec() {
   echo "WORKER_SPEC is ${WORKER_SPEC}"
 }
 
-set_worker_spec() {
+set_worker_spec () {
+  PS3="
+👉 Select worker spec : "
   select choice in "${built_in_specs[@]}"; do
     if [ "$REPLY" == "4" ]; then
-      set_custom_spec
+      set_custom_worker_spec
       break
     elif [ -n "$choice" ]; then
       WORKER_SPEC=${built_in_spec_map[$REPLY-1]}
@@ -460,8 +412,8 @@ set_worker_spec() {
 
 
 confirm_add_worker() {
-  read -p "Are you sure you want to add $WORKER_SIZE worker(s) to ${CONTEXT_NAME}-cluster? (y/n): " confirm
-  if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
+  read -p "Are you sure you want to add $WORKER_SIZE worker(s) to ${CLUSTER_NAME}-cluster? (Y/n): " confirm
+  if [ "$confirm" == "n" ] && [ "$confirm" == "N" ]; then
     echo "Exiting..."
     exit 0
   fi
@@ -469,7 +421,7 @@ confirm_add_worker() {
 
 
 set_master_name() {
-    MASTER_NAME=${CONTEXT_NAME}-master
+    MASTER_NAME=${CLUSTER_NAME}-master
     if [ -z $MASTER_NAME ]; then
         echo "Not found master name[$1]"
         exit 1
@@ -477,8 +429,8 @@ set_master_name() {
 }
 
 set_vm_image() {
-    VM_IMAGE=$(multipass ls | grep ^${CONTEXT_NAME}-master | awk '{print $5}')
-    if [ -z $VM_IMAGE ]; then
+    IMAGE_NAME=$(multipass ls | grep ^${CLUSTER_NAME}-master | awk '{print $5}')
+    if [ -z $IMAGE_NAME ]; then
         echo "Not found vm image[$1]"
         exit 1
     fi
@@ -486,8 +438,8 @@ set_vm_image() {
 
 set_worker_start_number() {
   LAST_WORKER_NUMBER=1
-  for i in $(multipass ls | grep ^${CONTEXT_NAME}-worker | wc -l | awk '{print $1}'); do
-    LAST_WORKER_NUMBER=$(sed -e "s/${CONTEXT_NAME}-worker//g" <<< "${i}")
+  for i in $(multipass ls | grep ^${CLUSTER_NAME}-worker | wc -l | awk '{print $1}'); do
+    LAST_WORKER_NUMBER=$(sed -e "s/${CLUSTER_NAME}-worker//g" <<< "${i}")
   done
 }
 
@@ -496,34 +448,32 @@ set_network_name() {
 }
 
 set_master_ip() {
-    MASTER_IP=$(multipass exec ${CONTEXT_NAME}-master -- hostname -I | awk '{print $1}')
+    MASTER_IP=$(multipass exec ${CLUSTER_NAME}-master -- hostname -I | awk '{print $1}')
 }
 
 set_node_token() {
-    NODE_TOKEN=$(multipass exec ${CONTEXT_NAME}-master -- sudo cat /var/lib/rancher/k3s/server/node-token)
+    NODE_TOKEN=$(multipass exec ${CLUSTER_NAME}-master -- sudo cat /var/lib/rancher/k3s/server/node-token)
 }
 
 set_start_end_number() {
     START_NUMBER=$(( $LAST_WORKER_NUMBER + 1 ))
     END_NUMBER=$(( $LAST_WORKER_NUMBER + $WORKER_SIZE))
-
-    echo "START_NUMBER is ${START_NUMBER}"
-    echo "END_NUMBER is ${END_NUMBER}"
+    # echo "START_NUMBER is ${START_NUMBER}"
+    # echo "END_NUMBER is ${END_NUMBER}"
 }
 
 create_workers() {
   for i in $(seq $START_NUMBER $END_NUMBER); do
     cat > .worker-${i}.yaml <<EOF
 package_update: true
-image: ${VM_IMAGE}
+image: ${IMAGE_NAME}
 packages:
   - curl
 runcmd:
   - curl -sfL https://get.k3s.io | K3S_URL=https://${MASTER_IP}:6443 K3S_TOKEN=${NODE_TOKEN} sh -
 EOF
 
-echo "${CONTEXT_NAME}-worker${i} ${WORKER_SPEC} ${NETWORK_NAME} ${VM_IMAGE}"
-    multipass launch --name ${CONTEXT_NAME}-worker${i} ${WORKER_SPEC} --network ${NETWORK_NAME} --cloud-init .worker-${i}.yaml
+    multipass launch ${IMAGE_NAME} --name ${CLUSTER_NAME}-worker${i} ${WORKER_SPEC} --network ${NETWORK_NAME} --cloud-init .worker-${i}.yaml
     rm -f ./.worker-${i}.yaml
   done
 }
@@ -532,23 +482,23 @@ print_cluster_state() {
   echo ""
   echo "📋 Cluster State:"
   echo "--------------------------------------------------------------------------------"
-  multipass exec ${CONTEXT_NAME}-master -- sudo kubectl get nodes
+  multipass exec ${CLUSTER_NAME}-master -- sudo kubectl get nodes
   echo "--------------------------------------------------------------------------------"
 }
 
 ###### Add Worker End ######
 
-create_cluster() {
-  validate_multipass_cmd
-  set_context_name
+generate_cluster() {
+  verify_multipass_cmd
+  set_cluster_name
   set_master_spec
   set_worker_size
   set_worker_spec
   set_network_name
   select_multipass_image
   set_install_k3s_exec
-  print_info
-  create_master
+  confirm_info
+  generate_master
   generate_workers
   create_k8s_config
 }
@@ -569,32 +519,36 @@ add_worker() {
   print_cluster_state
 }
 
+SUB_COMMAND=$1
 
-read_sub_command() {
-  PS3="
-  👉 Select a sub command (or 'q' to quit): "
+init_mpk3s() {
 
-  select choice in "${sub_commands[@]}"; do
-    if [[ "$REPLY" == "q" || "$REPLY" == "Q" ]]; then
-      echo "👋 Exiting..."
-      exit 0
-    elif [ -n "$choice" ]; then
-      SUB_COMMAND=${sub_commands[$REPLY-1]}
-      break
-    else
-      echo "⚠️ Invalid selection. Please enter a number from the list above."
-      exit 1
-    fi
-  done
+  if [ -z $SUB_COMMAND ]; then
+    PS3="
+👉 Select a sub command (or 'q' to quit): "
 
-  echo "Selected sub command: $SUB_COMMAND"
+    select choice in "${sub_commands[@]}"; do
+      if [[ "$REPLY" == "q" || "$REPLY" == "Q" ]]; then
+        echo "👋 Exiting..."
+        exit 0
+      elif [ -n "$choice" ]; then
+        SUB_COMMAND=${sub_commands[$REPLY-1]}
+        break
+      else
+        echo "⚠️ Invalid selection. Please enter a number from the list above."
+        exit 1
+      fi
+    done
+  fi
+
+  # echo "Selected sub command: $SUB_COMMAND"
 
   case $SUB_COMMAND in
     "init-kubeconfig")
       init_kubeconfig
       ;;
-    "create-cluster")
-      create_cluster
+    "generate-cluster")
+      generate_cluster
       ;;
     "add-worker")
       add_worker
@@ -612,4 +566,7 @@ read_sub_command() {
   esac
 }
 
-read_sub_command
+
+
+###### Main Start ######
+init_mpk3s
